all:
	g++ src/main.cpp -o main.exe \
		src/crypto/crypto.cpp \
		src/memory/memory.cpp \
		src/user/user.cpp \
		libs/imgui/*.cpp \
		src/handleGui/handlegui.cpp \
		-L libs/curl/lib \
		-I libs/curl/include/curl \
		-I libs/imgui -ld3d9 -ldwmapi -lgdi32 \
		-lcurl -lsqlite3