# all:
# 	g++ -o main.exe main.cpp -lcurl -LC:/CryptoScraper/curlLib/lib -IC:/CryptoScraper/curlLib/include

all:
	g++ -o main.exe main.cpp -lcurl -LC:/CryptoScraper/curlLib/lib -IC:/CryptoScraper/curlLib/include